// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA08mtNQOZAY5mqvtGzvGyc3JV2V20X3dc',
    appId: '1:127238456451:web:c5e7a05677858768fd87b6',
    messagingSenderId: '127238456451',
    projectId: 'smartcanteen-6e107',
    authDomain: 'smartcanteen-6e107.firebaseapp.com',
    storageBucket: 'smartcanteen-6e107.appspot.com',
    measurementId: 'G-3CN8YW3WCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDJ2pXBKL_uPedm4ZsPEr82fhiq5z3TQg',
    appId: '1:127238456451:android:4df972e020822489fd87b6',
    messagingSenderId: '127238456451',
    projectId: 'smartcanteen-6e107',
    storageBucket: 'smartcanteen-6e107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_-3Mq0KQsm8Z9IHeiJiKEfbWGzvC5Gfc',
    appId: '1:127238456451:ios:7155110d9c4aa308fd87b6',
    messagingSenderId: '127238456451',
    projectId: 'smartcanteen-6e107',
    storageBucket: 'smartcanteen-6e107.appspot.com',
    iosClientId:
        '127238456451-6lh8kjrg45l8s1rec7l8pjuvg62qhffj.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcanteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_-3Mq0KQsm8Z9IHeiJiKEfbWGzvC5Gfc',
    appId: '1:127238456451:ios:91d5bc87c321f9e5fd87b6',
    messagingSenderId: '127238456451',
    projectId: 'smartcanteen-6e107',
    storageBucket: 'smartcanteen-6e107.appspot.com',
    iosClientId:
        '127238456451-isljjscu0krbbsnei34k5190p4golhp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcanteen.RunnerTests',
  );
}
